### ISSUE TITLE
ERROR in app: Exception on / [GET]

### ISSUE THREAD

**Issue by kocane** [mc-17/pspack-flask#28]
I'm running, or trying to run, this on my old ODROID C2 (ARM device).

Seemingly starts up fine, requirements are installed (using Python 3.10) but when I access the site I get an "Internal server error" and the log output shows this:

```
[2022-11-16 19:33:10,225] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/apps/pspack-flask/app.py", line 74, in index
    if ")" in ua_part:
TypeError: argument of type 'NoneType' is not iterable
10.166.188.199 - - [16/Nov/2022 19:33:10] "GET / HTTP/1.1" 500 -
```

Any idea? or are ARM devices just not supported?

Thanks

**Comment by mc-17** [comment]
Hey

ARM shouldn't be a problem, I can see a small bug in the code but it shouldn't be occurring. Can you share your user agent from this link?

https://whatismyua.com/

**Comment by Eidigii** [comment]
I am having the exact same issue. Whenever I tried to visit from PS4 (on 9.0.0), I get: "This date is not supported by the PS4" and I get no logs.
When I visit from my browser on PC, I get the same logs as above:
```ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/app.py", line 74, in index
    if ")" in ua_part:
TypeError: argument of type 'NoneType' is not iterable```

**Comment by kocane** [comment]
> Hey
> 
> ARM shouldn't be a problem, I can see a small bug in the code but it shouldn't be occurring. Can you share your user agent from this link?
> 
> https://whatismyua.com/

The user agent from the PS4?

**Comment by mc-17** [comment]
> > Hey
> > ARM shouldn't be a problem, I can see a small bug in the code but it shouldn't be occurring. Can you share your user agent from this link?
> > https://whatismyua.com/
> 
> The user agent from the PS4?

Yeah

**Comment by mc-17** [comment]
No update - close
